export interface PageItem {
  index: number;
  imgUrl: string;
  className: string;
  mobileImgUrl: string;
  title: string;
  address: string;
}
export type PageItemWithPhotos = PageItem & { images: string[] };
export const data: PageItem[] = [
  {
    className: "",
    index: 0,
    imgUrl: "alnakheel/out/2.jpg",
    mobileImgUrl: "alnakheel/out/2.mobile.jpg",
    title: "مشروع منازل 102",
    address: "حي النخيل",
  },
  {
    className: "",
    index: 1,
    imgUrl: "morowa/out/1.jpg",
    mobileImgUrl: "morowa/out/1.m.jpg",
    title: "مشروع منازل المروة",
    address: "حي المروة",
  },
  {
    className: "",
    index: 2,
    imgUrl: "morowa/out/2.jpg",
    mobileImgUrl: "morowa/out/2.m.jpg",
    title: "مشروع منازل المروة",
    address: "حي المروة",
  },
  {
    className: "",
    index: 3,
    imgUrl: "morowa/out/3.jpg",
    mobileImgUrl: "morowa/out/3.m.jpg",
    title: "مشروع منازل المروة",
    address: "حي المروة",
  },
];
const morowaPhotos = [
  "morowa/in/DSC03380-HDR (1).jpg",
  "morowa/in/DSC03340-HDR.jpg",
  "morowa/in/DSC03345-HDR.jpg",
  "morowa/in/DSC03350-HDR.jpg",
  "morowa/in/DSC03355-HDR.jpg",
  "morowa/in/DSC03360-HDR.jpg",
  "morowa/in/DSC03365-HDR.jpg",
  "morowa/in/DSC03370-HDR.jpg",
  "morowa/in/DSC03375-HDR.jpg",
  "morowa/in/DSC03380-HDR.jpg",
  "morowa/in/DSC03385-HDR.jpg",
  "morowa/in/DSC03390-HDR.jpg",
  "morowa/in/DSC03395-HDR.jpg",
  "morowa/in/DSC03400-HDR.jpg",
  "morowa/in/DSC03405-HDR.jpg",
  "morowa/in/DSC03410-HDR.jpg",
  "morowa/in/DSC03415-HDR.jpg",
  "morowa/in/DSC03420-HDR.jpg",
  "morowa/in/DSC03425-HDR.jpg",
  "morowa/in/DSC03430-HDR.jpg",
  "morowa/in/DSC03435-HDR.jpg",
  "morowa/in/DSC03440-HDR.jpg",
  "morowa/in/DSC03445-HDR.jpg",
  "morowa/in/DSC03450-HDR.jpg",
  "morowa/in/DSC03455-HDR.jpg",
];
const alnakheelPhotos = [
  "DSC02840-HDR.jpg",
  "alnakheel/in/DSC02845-HDR.jpg",
  "alnakheel/in/DSC02850-HDR.jpg",
  "alnakheel/in/DSC02855-HDR.jpg",
  "alnakheel/in/DSC02860-HDR.jpg",
  "alnakheel/in/DSC02865-HDR.jpg",
  "alnakheel/in/DSC02870-HDR.jpg",
  "alnakheel/in/DSC02875-HDR.jpg",
  "alnakheel/in/DSC02880-HDR.jpg",
  "alnakheel/in/DSC02885-HDR.jpg",
  "alnakheel/in/DSC02890-HDR.jpg",
  "alnakheel/in/DSC02895-HDR.jpg",
  "alnakheel/in/DSC02900-HDR.jpg",
  "alnakheel/in/DSC02905-HDR.jpg",
  "alnakheel/in/DSC02910-HDR.jpg",
  "alnakheel/in/DSC02915-HDR.jpg",
  "alnakheel/in/DSC02920-HDR.jpg",
  "alnakheel/in/DSC02925-HDR.jpg",
  "alnakheel/in/DSC02930-HDR.jpg",
  "alnakheel/in/DSC02935-HDR.jpg",
  "alnakheel/in/DSC02940-HDR.jpg",
  "alnakheel/in/DSC02945-HDR.jpg",
  "alnakheel/in/DSC02950-HDR.jpg",
  "alnakheel/in/DSC02955-HDR.jpg",
  "alnakheel/in/DSC02960-HDR.jpg",
  "alnakheel/in/DSC02965-HDR.jpg",
  "alnakheel/in/DSC02970-HDR.jpg",
  "alnakheel/in/DSC02975-HDR.jpg",
  "alnakheel/in/DSC02980-HDR.jpg",
  "alnakheel/in/DSC02985-HDR.jpg",
];

export const data2: PageItemWithPhotos[] = [
  {
    className: "",
    index: 0,
    imgUrl: "./alnakheel/out/1.jpg",
    mobileImgUrl: "./alnakheel/out/1.jpg",
    title: "مشروع منازل 102",
    address: "حي النخيل",
    images: alnakheelPhotos,
  },
  {
    className: "",
    index: 1,
    imgUrl: "./morowa/out/1.jpg",
    mobileImgUrl: "./morowa/out/1.m.jpg",
    title: "مشروع منازل المروة",
    address: "حي المروة",
    images: morowaPhotos,
  },
  {
    className: "",
    index: 2,
    imgUrl: "./morowa/out/2.jpg",
    mobileImgUrl: "./morowa/out/2.m.jpg",
    title: "مشروع منازل المروة",
    address: "حي المروة",
    images: morowaPhotos,
  },
  {
    className: "",
    index: 3,
    imgUrl: "./morowa/out/3.jpg",
    mobileImgUrl: "./morowa/out/3.m.jpg",
    title: "مشروع منازل المروة",
    address: "حي المروة",
    images: morowaPhotos,
  },
];
